//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;
using AutoMapper;

namespace GithubDeployTest;
// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class NewDataSet
{

    private object[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("kalkulationsstruktur", typeof(NewDataSetKalkulationsstruktur), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("projektartikelkalkulation", typeof(NewDataSetProjektartikelkalkulation), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("projektkosten", typeof(NewDataSetProjektkosten), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }

    public ListDataSet GetList()
    {
        var config = new MapperConfiguration(cfg => cfg.AddProfile<MappingProfile>());
        IMapper mapper = new Mapper(config);
        ListDataSet DataSetList = new ListDataSet();

        foreach (NewDataSetKalkulationsstruktur Position in this.Items.OfType<NewDataSetKalkulationsstruktur>().ToList())
        {
            ListKalkulationsstruktur NewPosition = mapper.Map<ListKalkulationsstruktur>(Position);

            foreach (NewDataSetProjektkosten Kosten in this.Items.OfType<NewDataSetProjektkosten>().Where(n => n.PosNr == NewPosition.PosNr))
            {
                ListProjektkosten NewProjektkosten = mapper.Map<ListProjektkosten>(Kosten);

                foreach (NewDataSetProjektartikelkalkulation Artikel in this.Items.OfType<NewDataSetProjektartikelkalkulation>().Where(n => n.KstID == NewProjektkosten.ID))
                {
                    ListProjektArtikelKosten NewProjektArtikelKosten = mapper.Map<ListProjektArtikelKosten>(Artikel);

                    NewProjektkosten.ProjektArtikel.Add(NewProjektArtikelKosten);

                }
                NewPosition.Projektkosten.Add(NewProjektkosten);
            }

            DataSetList.Kalkulation.Add(NewPosition);
        }
        return DataSetList;
    }
}

public class MappingProfile : Profile
{
    public MappingProfile()
    {
        CreateMap<NewDataSetKalkulationsstruktur, ListKalkulationsstruktur>().ForMember(dest => dest.Projektkosten, opt => opt.Ignore()).ForMember(dest => dest.ShowDetails, opt => opt.Ignore()); // Projektkosten wird nicht gemappt
        CreateMap<NewDataSetProjektkosten, ListProjektkosten>().ForMember(dest => dest.ProjektArtikel, opt => opt.Ignore()); // ProjektArtikel wird nicht gemappt
        CreateMap<NewDataSetProjektartikelkalkulation, ListProjektArtikelKosten>();
    }
}

public partial class ListDataSet : NewDataSet
{
    public List<ListKalkulationsstruktur> Kalkulation
    {
        get; set;
    } = new List<ListKalkulationsstruktur>();


}
public partial class ListKalkulationsstruktur : NewDataSetKalkulationsstruktur
{
    public List<ListProjektkosten> Projektkosten
    {
        get; set;
    } = new List<ListProjektkosten>();
    public bool ShowDetails
    {
        get; set;
    } = false;

}
public partial class ListProjektkosten : NewDataSetProjektkosten
{
    public List<ListProjektArtikelKosten> ProjektArtikel
    {
        get; set;
    } = new List<ListProjektArtikelKosten>();
}
public partial class ListProjektArtikelKosten : NewDataSetProjektartikelkalkulation
{

}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class NewDataSetKalkulationsstruktur
{

    private int posNrField;

    private bool posNrFieldSpecified;

    private string kommissionsNrField;

    private string positionField;

    private double anzahlField;

    private bool anzahlFieldSpecified;

    private string bezeichnungField;

    private string beschreibungField;

    private string mengenEinheitField;

    private string bild1Field;

    private string bild2Field;

    private string bild3Field;

    private string bild4Field;

    private string bild5Field;

    private bool bedarfspositionField;

    private bool bedarfspositionFieldSpecified;

    private bool verteiltField;

    private bool verteiltFieldSpecified;

    private byte[] rOIDField;

    private bool nachtragspositionField;

    private bool nachtragspositionFieldSpecified;

    private int breiteField;

    private bool breiteFieldSpecified;

    private int höheField;

    private bool höheFieldSpecified;

    private decimal flächeField;

    private bool flächeFieldSpecified;

    private int angDetIDField;

    private bool angDetIDFieldSpecified;

    private bool beauftragtField;

    private bool beauftragtFieldSpecified;

    private int ebeneField;

    private bool ebeneFieldSpecified;

    private int parentField;

    private bool parentFieldSpecified;

    private int orderColumnField;

    private bool orderColumnFieldSpecified;

    private bool nKrelevantField;

    private bool nKrelevantFieldSpecified;

    private System.DateTime erstellt_amField;

    private bool erstellt_amFieldSpecified;

    private string erstellt_durchField;

    private bool rechnungspositionField;

    private bool rechnungspositionFieldSpecified;

    private double nachlassProzentField;

    private bool nachlassProzentFieldSpecified;

    private int aBDetIDField;

    private bool aBDetIDFieldSpecified;

    private short markierungField;

    private bool markierungFieldSpecified;

    private string bild1_TextField;

    private int positionstypField;

    private bool positionstypFieldSpecified;

    private string scItemIDField;

    private string scJobIDField;

    private System.DateTime lastChangedField;

    private bool lastChangedFieldSpecified;

    private bool isGaebPosField;

    private bool isGaebPosFieldSpecified;

    private string oRGAField;

    private bool pauschaliertField;

    private bool pauschaliertFieldSpecified;

    private double anzahlBeauftragtField;

    private bool anzahlBeauftragtFieldSpecified;

    private string warengruppeField;

    private short textFlagField;

    private bool textFlagFieldSpecified;

    private decimal intrastatGewichtField;

    private bool intrastatGewichtFieldSpecified;

    private string versionGUIDField;

    private System.DateTime freigabe_amField;

    private bool freigabe_amFieldSpecified;

    private string guidIDField;

    private string freigabe_durchField;

    private int positionsstatusField;

    private bool positionsstatusFieldSpecified;

    private System.DateTime lastSyncedField;

    private bool lastSyncedFieldSpecified;

    private string zeichnungsnummerField;

    private string kdArtikelNrField;

    private string oberflaecheField;

    private string systembezeichnungField;

    private bool warBedarfField;

    private bool warBedarfFieldSpecified;

    private bool gewinnAusArtikelVKPreisField;

    private bool gewinnAusArtikelVKPreisFieldSpecified;

    private int beschreibungTextIDField;

    private bool beschreibungTextIDFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Pos-Nr", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int PosNr
    {
        get
        {
            return this.posNrField;
        }
        set
        {
            this.posNrField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PosNrSpecified
    {
        get
        {
            return this.posNrFieldSpecified;
        }
        set
        {
            this.posNrFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Kommissions-Nr", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string KommissionsNr
    {
        get
        {
            return this.kommissionsNrField;
        }
        set
        {
            this.kommissionsNrField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Position
    {
        get
        {
            return this.positionField;
        }
        set
        {
            this.positionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double Anzahl
    {
        get
        {
            return this.anzahlField;
        }
        set
        {
            this.anzahlField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AnzahlSpecified
    {
        get
        {
            return this.anzahlFieldSpecified;
        }
        set
        {
            this.anzahlFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Bezeichnung
    {
        get
        {
            return this.bezeichnungField;
        }
        set
        {
            this.bezeichnungField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Beschreibung
    {
        get
        {
            return this.beschreibungField;
        }
        set
        {
            this.beschreibungField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MengenEinheit
    {
        get
        {
            return this.mengenEinheitField;
        }
        set
        {
            this.mengenEinheitField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Bild1
    {
        get
        {
            return this.bild1Field;
        }
        set
        {
            this.bild1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Bild2
    {
        get
        {
            return this.bild2Field;
        }
        set
        {
            this.bild2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Bild3
    {
        get
        {
            return this.bild3Field;
        }
        set
        {
            this.bild3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Bild4
    {
        get
        {
            return this.bild4Field;
        }
        set
        {
            this.bild4Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Bild5
    {
        get
        {
            return this.bild5Field;
        }
        set
        {
            this.bild5Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool Bedarfsposition
    {
        get
        {
            return this.bedarfspositionField;
        }
        set
        {
            this.bedarfspositionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BedarfspositionSpecified
    {
        get
        {
            return this.bedarfspositionFieldSpecified;
        }
        set
        {
            this.bedarfspositionFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool Verteilt
    {
        get
        {
            return this.verteiltField;
        }
        set
        {
            this.verteiltField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VerteiltSpecified
    {
        get
        {
            return this.verteiltFieldSpecified;
        }
        set
        {
            this.verteiltFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "base64Binary")]
    public byte[] ROID
    {
        get
        {
            return this.rOIDField;
        }
        set
        {
            this.rOIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool Nachtragsposition
    {
        get
        {
            return this.nachtragspositionField;
        }
        set
        {
            this.nachtragspositionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NachtragspositionSpecified
    {
        get
        {
            return this.nachtragspositionFieldSpecified;
        }
        set
        {
            this.nachtragspositionFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Breite
    {
        get
        {
            return this.breiteField;
        }
        set
        {
            this.breiteField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BreiteSpecified
    {
        get
        {
            return this.breiteFieldSpecified;
        }
        set
        {
            this.breiteFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Höhe
    {
        get
        {
            return this.höheField;
        }
        set
        {
            this.höheField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HöheSpecified
    {
        get
        {
            return this.höheFieldSpecified;
        }
        set
        {
            this.höheFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Fläche
    {
        get
        {
            return this.flächeField;
        }
        set
        {
            this.flächeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FlächeSpecified
    {
        get
        {
            return this.flächeFieldSpecified;
        }
        set
        {
            this.flächeFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int AngDetID
    {
        get
        {
            return this.angDetIDField;
        }
        set
        {
            this.angDetIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AngDetIDSpecified
    {
        get
        {
            return this.angDetIDFieldSpecified;
        }
        set
        {
            this.angDetIDFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool Beauftragt
    {
        get
        {
            return this.beauftragtField;
        }
        set
        {
            this.beauftragtField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BeauftragtSpecified
    {
        get
        {
            return this.beauftragtFieldSpecified;
        }
        set
        {
            this.beauftragtFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Ebene
    {
        get
        {
            return this.ebeneField;
        }
        set
        {
            this.ebeneField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EbeneSpecified
    {
        get
        {
            return this.ebeneFieldSpecified;
        }
        set
        {
            this.ebeneFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Parent
    {
        get
        {
            return this.parentField;
        }
        set
        {
            this.parentField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ParentSpecified
    {
        get
        {
            return this.parentFieldSpecified;
        }
        set
        {
            this.parentFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int OrderColumn
    {
        get
        {
            return this.orderColumnField;
        }
        set
        {
            this.orderColumnField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OrderColumnSpecified
    {
        get
        {
            return this.orderColumnFieldSpecified;
        }
        set
        {
            this.orderColumnFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool NKrelevant
    {
        get
        {
            return this.nKrelevantField;
        }
        set
        {
            this.nKrelevantField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NKrelevantSpecified
    {
        get
        {
            return this.nKrelevantFieldSpecified;
        }
        set
        {
            this.nKrelevantFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime Erstellt_am
    {
        get
        {
            return this.erstellt_amField;
        }
        set
        {
            this.erstellt_amField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Erstellt_amSpecified
    {
        get
        {
            return this.erstellt_amFieldSpecified;
        }
        set
        {
            this.erstellt_amFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Erstellt_durch
    {
        get
        {
            return this.erstellt_durchField;
        }
        set
        {
            this.erstellt_durchField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool Rechnungsposition
    {
        get
        {
            return this.rechnungspositionField;
        }
        set
        {
            this.rechnungspositionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RechnungspositionSpecified
    {
        get
        {
            return this.rechnungspositionFieldSpecified;
        }
        set
        {
            this.rechnungspositionFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double NachlassProzent
    {
        get
        {
            return this.nachlassProzentField;
        }
        set
        {
            this.nachlassProzentField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NachlassProzentSpecified
    {
        get
        {
            return this.nachlassProzentFieldSpecified;
        }
        set
        {
            this.nachlassProzentFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int ABDetID
    {
        get
        {
            return this.aBDetIDField;
        }
        set
        {
            this.aBDetIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ABDetIDSpecified
    {
        get
        {
            return this.aBDetIDFieldSpecified;
        }
        set
        {
            this.aBDetIDFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public short Markierung
    {
        get
        {
            return this.markierungField;
        }
        set
        {
            this.markierungField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MarkierungSpecified
    {
        get
        {
            return this.markierungFieldSpecified;
        }
        set
        {
            this.markierungFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Bild1_Text
    {
        get
        {
            return this.bild1_TextField;
        }
        set
        {
            this.bild1_TextField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Positionstyp
    {
        get
        {
            return this.positionstypField;
        }
        set
        {
            this.positionstypField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PositionstypSpecified
    {
        get
        {
            return this.positionstypFieldSpecified;
        }
        set
        {
            this.positionstypFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string scItemID
    {
        get
        {
            return this.scItemIDField;
        }
        set
        {
            this.scItemIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string scJobID
    {
        get
        {
            return this.scJobIDField;
        }
        set
        {
            this.scJobIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime LastChanged
    {
        get
        {
            return this.lastChangedField;
        }
        set
        {
            this.lastChangedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LastChangedSpecified
    {
        get
        {
            return this.lastChangedFieldSpecified;
        }
        set
        {
            this.lastChangedFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool IsGaebPos
    {
        get
        {
            return this.isGaebPosField;
        }
        set
        {
            this.isGaebPosField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsGaebPosSpecified
    {
        get
        {
            return this.isGaebPosFieldSpecified;
        }
        set
        {
            this.isGaebPosFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ORGA
    {
        get
        {
            return this.oRGAField;
        }
        set
        {
            this.oRGAField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool Pauschaliert
    {
        get
        {
            return this.pauschaliertField;
        }
        set
        {
            this.pauschaliertField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PauschaliertSpecified
    {
        get
        {
            return this.pauschaliertFieldSpecified;
        }
        set
        {
            this.pauschaliertFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double AnzahlBeauftragt
    {
        get
        {
            return this.anzahlBeauftragtField;
        }
        set
        {
            this.anzahlBeauftragtField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AnzahlBeauftragtSpecified
    {
        get
        {
            return this.anzahlBeauftragtFieldSpecified;
        }
        set
        {
            this.anzahlBeauftragtFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Warengruppe
    {
        get
        {
            return this.warengruppeField;
        }
        set
        {
            this.warengruppeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public short TextFlag
    {
        get
        {
            return this.textFlagField;
        }
        set
        {
            this.textFlagField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TextFlagSpecified
    {
        get
        {
            return this.textFlagFieldSpecified;
        }
        set
        {
            this.textFlagFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal IntrastatGewicht
    {
        get
        {
            return this.intrastatGewichtField;
        }
        set
        {
            this.intrastatGewichtField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IntrastatGewichtSpecified
    {
        get
        {
            return this.intrastatGewichtFieldSpecified;
        }
        set
        {
            this.intrastatGewichtFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VersionGUID
    {
        get
        {
            return this.versionGUIDField;
        }
        set
        {
            this.versionGUIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime Freigabe_am
    {
        get
        {
            return this.freigabe_amField;
        }
        set
        {
            this.freigabe_amField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Freigabe_amSpecified
    {
        get
        {
            return this.freigabe_amFieldSpecified;
        }
        set
        {
            this.freigabe_amFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GuidID
    {
        get
        {
            return this.guidIDField;
        }
        set
        {
            this.guidIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Freigabe_durch
    {
        get
        {
            return this.freigabe_durchField;
        }
        set
        {
            this.freigabe_durchField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Positionsstatus
    {
        get
        {
            return this.positionsstatusField;
        }
        set
        {
            this.positionsstatusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PositionsstatusSpecified
    {
        get
        {
            return this.positionsstatusFieldSpecified;
        }
        set
        {
            this.positionsstatusFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime LastSynced
    {
        get
        {
            return this.lastSyncedField;
        }
        set
        {
            this.lastSyncedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LastSyncedSpecified
    {
        get
        {
            return this.lastSyncedFieldSpecified;
        }
        set
        {
            this.lastSyncedFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Zeichnungsnummer
    {
        get
        {
            return this.zeichnungsnummerField;
        }
        set
        {
            this.zeichnungsnummerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string KdArtikelNr
    {
        get
        {
            return this.kdArtikelNrField;
        }
        set
        {
            this.kdArtikelNrField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Oberflaeche
    {
        get
        {
            return this.oberflaecheField;
        }
        set
        {
            this.oberflaecheField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Systembezeichnung
    {
        get
        {
            return this.systembezeichnungField;
        }
        set
        {
            this.systembezeichnungField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool WarBedarf
    {
        get
        {
            return this.warBedarfField;
        }
        set
        {
            this.warBedarfField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WarBedarfSpecified
    {
        get
        {
            return this.warBedarfFieldSpecified;
        }
        set
        {
            this.warBedarfFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool GewinnAusArtikelVKPreis
    {
        get
        {
            return this.gewinnAusArtikelVKPreisField;
        }
        set
        {
            this.gewinnAusArtikelVKPreisField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GewinnAusArtikelVKPreisSpecified
    {
        get
        {
            return this.gewinnAusArtikelVKPreisFieldSpecified;
        }
        set
        {
            this.gewinnAusArtikelVKPreisFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int BeschreibungTextID
    {
        get
        {
            return this.beschreibungTextIDField;
        }
        set
        {
            this.beschreibungTextIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BeschreibungTextIDSpecified
    {
        get
        {
            return this.beschreibungTextIDFieldSpecified;
        }
        set
        {
            this.beschreibungTextIDFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class NewDataSetProjektartikelkalkulation
{

    private int idField;

    private bool idFieldSpecified;

    private int kstIDField;

    private bool kstIDFieldSpecified;

    private string artikelNrField;

    private string artikelbezeichnungField;

    private double mengeField;

    private bool mengeFieldSpecified;

    private string mengenEinheitField;

    private short mengentypField;

    private bool mengentypFieldSpecified;

    private decimal listenpreisField;

    private bool listenpreisFieldSpecified;

    private decimal breiteField;

    private bool breiteFieldSpecified;

    private decimal höheField;

    private bool höheFieldSpecified;

    private decimal längeField;

    private bool längeFieldSpecified;

    private decimal gewichtField;

    private bool gewichtFieldSpecified;

    private decimal gesamtpreisField;

    private bool gesamtpreisFieldSpecified;

    private string oberfl_InnField;

    private string oberfl_AusField;

    private double qmField;

    private bool qmFieldSpecified;

    private string basisField;

    private string basis2Field;

    private bool fixField;

    private bool fixFieldSpecified;

    private string kennz1Field;

    private string kennz2Field;

    private string kennz3Field;

    private bool lieferungField;

    private bool lieferungFieldSpecified;

    private string bemerkungField;

    private string dstvTeilenummerField;

    private string dstvBauteilField;

    private string dstvCharakteristikField;

    private string dstvVorbestellNrField;

    private int auftragszeitenIDField;

    private bool auftragszeitenIDFieldSpecified;

    private string basis3Field;

    private string basis4Field;

    private decimal vKPreisField;

    private bool vKPreisFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IDSpecified
    {
        get
        {
            return this.idFieldSpecified;
        }
        set
        {
            this.idFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int KstID
    {
        get
        {
            return this.kstIDField;
        }
        set
        {
            this.kstIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool KstIDSpecified
    {
        get
        {
            return this.kstIDFieldSpecified;
        }
        set
        {
            this.kstIDFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Artikel-Nr", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ArtikelNr
    {
        get
        {
            return this.artikelNrField;
        }
        set
        {
            this.artikelNrField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Artikelbezeichnung
    {
        get
        {
            return this.artikelbezeichnungField;
        }
        set
        {
            this.artikelbezeichnungField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double Menge
    {
        get
        {
            return this.mengeField;
        }
        set
        {
            this.mengeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MengeSpecified
    {
        get
        {
            return this.mengeFieldSpecified;
        }
        set
        {
            this.mengeFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MengenEinheit
    {
        get
        {
            return this.mengenEinheitField;
        }
        set
        {
            this.mengenEinheitField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public short Mengentyp
    {
        get
        {
            return this.mengentypField;
        }
        set
        {
            this.mengentypField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MengentypSpecified
    {
        get
        {
            return this.mengentypFieldSpecified;
        }
        set
        {
            this.mengentypFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Listenpreis
    {
        get
        {
            return this.listenpreisField;
        }
        set
        {
            this.listenpreisField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ListenpreisSpecified
    {
        get
        {
            return this.listenpreisFieldSpecified;
        }
        set
        {
            this.listenpreisFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Breite
    {
        get
        {
            return this.breiteField;
        }
        set
        {
            this.breiteField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BreiteSpecified
    {
        get
        {
            return this.breiteFieldSpecified;
        }
        set
        {
            this.breiteFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Höhe
    {
        get
        {
            return this.höheField;
        }
        set
        {
            this.höheField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HöheSpecified
    {
        get
        {
            return this.höheFieldSpecified;
        }
        set
        {
            this.höheFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Länge
    {
        get
        {
            return this.längeField;
        }
        set
        {
            this.längeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LängeSpecified
    {
        get
        {
            return this.längeFieldSpecified;
        }
        set
        {
            this.längeFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Gewicht
    {
        get
        {
            return this.gewichtField;
        }
        set
        {
            this.gewichtField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GewichtSpecified
    {
        get
        {
            return this.gewichtFieldSpecified;
        }
        set
        {
            this.gewichtFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Gesamtpreis
    {
        get
        {
            return this.gesamtpreisField;
        }
        set
        {
            this.gesamtpreisField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GesamtpreisSpecified
    {
        get
        {
            return this.gesamtpreisFieldSpecified;
        }
        set
        {
            this.gesamtpreisFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Oberfl_Inn
    {
        get
        {
            return this.oberfl_InnField;
        }
        set
        {
            this.oberfl_InnField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Oberfl_Aus
    {
        get
        {
            return this.oberfl_AusField;
        }
        set
        {
            this.oberfl_AusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double qm
    {
        get
        {
            return this.qmField;
        }
        set
        {
            this.qmField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool qmSpecified
    {
        get
        {
            return this.qmFieldSpecified;
        }
        set
        {
            this.qmFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Basis
    {
        get
        {
            return this.basisField;
        }
        set
        {
            this.basisField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Basis2
    {
        get
        {
            return this.basis2Field;
        }
        set
        {
            this.basis2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool Fix
    {
        get
        {
            return this.fixField;
        }
        set
        {
            this.fixField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FixSpecified
    {
        get
        {
            return this.fixFieldSpecified;
        }
        set
        {
            this.fixFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Kennz1
    {
        get
        {
            return this.kennz1Field;
        }
        set
        {
            this.kennz1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Kennz2
    {
        get
        {
            return this.kennz2Field;
        }
        set
        {
            this.kennz2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Kennz3
    {
        get
        {
            return this.kennz3Field;
        }
        set
        {
            this.kennz3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool Lieferung
    {
        get
        {
            return this.lieferungField;
        }
        set
        {
            this.lieferungField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LieferungSpecified
    {
        get
        {
            return this.lieferungFieldSpecified;
        }
        set
        {
            this.lieferungFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Bemerkung
    {
        get
        {
            return this.bemerkungField;
        }
        set
        {
            this.bemerkungField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DstvTeilenummer
    {
        get
        {
            return this.dstvTeilenummerField;
        }
        set
        {
            this.dstvTeilenummerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DstvBauteil
    {
        get
        {
            return this.dstvBauteilField;
        }
        set
        {
            this.dstvBauteilField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DstvCharakteristik
    {
        get
        {
            return this.dstvCharakteristikField;
        }
        set
        {
            this.dstvCharakteristikField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DstvVorbestellNr
    {
        get
        {
            return this.dstvVorbestellNrField;
        }
        set
        {
            this.dstvVorbestellNrField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int AuftragszeitenID
    {
        get
        {
            return this.auftragszeitenIDField;
        }
        set
        {
            this.auftragszeitenIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AuftragszeitenIDSpecified
    {
        get
        {
            return this.auftragszeitenIDFieldSpecified;
        }
        set
        {
            this.auftragszeitenIDFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Basis3
    {
        get
        {
            return this.basis3Field;
        }
        set
        {
            this.basis3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Basis4
    {
        get
        {
            return this.basis4Field;
        }
        set
        {
            this.basis4Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal VKPreis
    {
        get
        {
            return this.vKPreisField;
        }
        set
        {
            this.vKPreisField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VKPreisSpecified
    {
        get
        {
            return this.vKPreisFieldSpecified;
        }
        set
        {
            this.vKPreisFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class NewDataSetProjektkosten
{

    private int idField;

    private bool idFieldSpecified;

    private int posNrField;

    private bool posNrFieldSpecified;

    private string kostenartField;

    private string bezeichnungField;

    private decimal wertField;

    private bool wertFieldSpecified;

    private double stundenField;

    private bool stundenFieldSpecified;

    private byte[] rOIDField;

    private string groupField;

    private decimal mengeField;

    private bool mengeFieldSpecified;

    private int kosttypField;

    private bool kosttypFieldSpecified;

    private string interfaceTypeField;

    private string groupUnitField;

    private decimal groupWidthField;

    private bool groupWidthFieldSpecified;

    private decimal groupHeightField;

    private bool groupHeightFieldSpecified;

    private string basisField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IDSpecified
    {
        get
        {
            return this.idFieldSpecified;
        }
        set
        {
            this.idFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Pos-Nr", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int PosNr
    {
        get
        {
            return this.posNrField;
        }
        set
        {
            this.posNrField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PosNrSpecified
    {
        get
        {
            return this.posNrFieldSpecified;
        }
        set
        {
            this.posNrFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Kostenart
    {
        get
        {
            return this.kostenartField;
        }
        set
        {
            this.kostenartField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Bezeichnung
    {
        get
        {
            return this.bezeichnungField;
        }
        set
        {
            this.bezeichnungField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Wert
    {
        get
        {
            return this.wertField;
        }
        set
        {
            this.wertField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WertSpecified
    {
        get
        {
            return this.wertFieldSpecified;
        }
        set
        {
            this.wertFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double Stunden
    {
        get
        {
            return this.stundenField;
        }
        set
        {
            this.stundenField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StundenSpecified
    {
        get
        {
            return this.stundenFieldSpecified;
        }
        set
        {
            this.stundenFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "base64Binary")]
    public byte[] ROID
    {
        get
        {
            return this.rOIDField;
        }
        set
        {
            this.rOIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Group
    {
        get
        {
            return this.groupField;
        }
        set
        {
            this.groupField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Menge
    {
        get
        {
            return this.mengeField;
        }
        set
        {
            this.mengeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MengeSpecified
    {
        get
        {
            return this.mengeFieldSpecified;
        }
        set
        {
            this.mengeFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Kosttyp
    {
        get
        {
            return this.kosttypField;
        }
        set
        {
            this.kosttypField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool KosttypSpecified
    {
        get
        {
            return this.kosttypFieldSpecified;
        }
        set
        {
            this.kosttypFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InterfaceType
    {
        get
        {
            return this.interfaceTypeField;
        }
        set
        {
            this.interfaceTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GroupUnit
    {
        get
        {
            return this.groupUnitField;
        }
        set
        {
            this.groupUnitField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal GroupWidth
    {
        get
        {
            return this.groupWidthField;
        }
        set
        {
            this.groupWidthField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GroupWidthSpecified
    {
        get
        {
            return this.groupWidthFieldSpecified;
        }
        set
        {
            this.groupWidthFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal GroupHeight
    {
        get
        {
            return this.groupHeightField;
        }
        set
        {
            this.groupHeightField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GroupHeightSpecified
    {
        get
        {
            return this.groupHeightFieldSpecified;
        }
        set
        {
            this.groupHeightFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Basis
    {
        get
        {
            return this.basisField;
        }
        set
        {
            this.basisField = value;
        }
    }
}
